-- Supabase SQL to create actions_log table and storage bucket

create table if not exists public.actions_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  file_key text not null,
  action_type text not null check (action_type in ('upload','compress','merge','split','sign')),
  details jsonb,
  created_at timestamp with time zone not null default now()
);

-- Create storage bucket for PDFs (run in Supabase Storage UI or via API)
-- In SQL, you can use the storage schema if enabled:
-- select storage.create_bucket('pdfs', public => true);

-- Row Level Security: allow users to read only their rows
alter table public.actions_log enable row level security;
create policy if not exists "own rows" on public.actions_log for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

